version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - celery_worker
      - celery_beat

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_USER: your_postgres_user
      POSTGRES_DB: your_postgres_db_name

  redis:
    image: redis:latest

  celery_worker:
    build:
      context: .
      dockerfile: ./server/Dockerfile  # Use the same Dockerfile for worker
    command: celery -A ecommerce_application worker -l info
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./server/Dockerfile  # Use the same Dockerfile for beat
    command: celery -A ecommerce_application beat -l info
    depends_on:
      - redis
      - db

volumes:
  postgres_data: