/*
 Navicat Premium Data Transfer

 Source Server         : docker_db
 Source Server Type    : PostgreSQL
 Source Server Version : 170002 (170002)
 Source Host           : localhost:5433
 Source Catalog        : ecommerce
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 170002 (170002)
 File Encoding         : 65001

 Date: 07/01/2025 10:11:14
*/


-- ----------------------------
-- Table structure for core_user
-- ----------------------------
DROP TABLE IF EXISTS "public"."core_user";
CREATE TABLE "public"."core_user" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "password" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
  "is_superuser" bool NOT NULL,
  "first_name" varchar(30) COLLATE "pg_catalog"."default",
  "last_name" varchar(30) COLLATE "pg_catalog"."default",
  "email" varchar(254) COLLATE "pg_catalog"."default" NOT NULL,
  "phone" varchar(15) COLLATE "pg_catalog"."default",
  "is_active" bool NOT NULL,
  "is_staff" bool NOT NULL,
  "is_verified" bool NOT NULL,
  "last_login" timestamptz(6),
  "avatar" varchar(100) COLLATE "pg_catalog"."default",
  "role_id" int8,
  "permissions" jsonb NOT NULL,
  "created_at" timestamptz(6) NOT NULL,
  "updated_at" timestamptz(6) NOT NULL
)
;

-- ----------------------------
-- Records of core_user
-- ----------------------------
INSERT INTO "public"."core_user" VALUES (1, 'pbkdf2_sha256$870000$vcePrEqgnlqecCaKavFYs9$Tq4P5w5/+0nNc0qh45GuG2OK1jRxKo7MQVDAlxxuOm8=', 'f', 'muhammad', 'taneem', 'taneem71@gmail.com', NULL, 'f', 'f', 'f', NULL, '', 1, '[]', '2025-01-07 03:34:58.267829+00', '2025-01-07 03:34:59.017265+00');

-- ----------------------------
-- Auto increment value for core_user
-- ----------------------------
SELECT setval('"public"."core_user_id_seq"', 1, true);

-- ----------------------------
-- Indexes structure for table core_user
-- ----------------------------
CREATE INDEX "core_user_email_92a71487_like" ON "public"."core_user" USING btree (
  "email" COLLATE "pg_catalog"."default" "pg_catalog"."varchar_pattern_ops" ASC NULLS LAST
);
CREATE INDEX "core_user_role_id_8de62872" ON "public"."core_user" USING btree (
  "role_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);

-- ----------------------------
-- Uniques structure for table core_user
-- ----------------------------
ALTER TABLE "public"."core_user" ADD CONSTRAINT "core_user_email_key" UNIQUE ("email");

-- ----------------------------
-- Primary Key structure for table core_user
-- ----------------------------
ALTER TABLE "public"."core_user" ADD CONSTRAINT "core_user_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table core_user
-- ----------------------------
ALTER TABLE "public"."core_user" ADD CONSTRAINT "core_user_role_id_8de62872_fk_core_role_id" FOREIGN KEY ("role_id") REFERENCES "public"."core_role" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
